version: '3'
 
services:
  reverse-proxy:
    image: traefik:1.7.11-alpine
    restart: always
    container_name: traefik
    ports:
      - 8080:8080
      - 80:80
      - 443:443
    networks:
      - traefik
    command: traefik -c /etc/traefik.toml
    volumes:
# 仅限标准的 Linux 环境
#      - /etc/localtime:/etc/localtime
#      - /etc/timezone:/etc/timezone
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./logs:/data/logs
      - ./acme.json:/acme.json
 
networks:
  traefik:
    external: true